---
version: '3.2'

networks:
  jenkins:
  kind:
    external:
      name: kind

volumes:
  filebeat_data: {}

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.5
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data:/var/lib/grafana
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.26.0
    ports:
      - 9090:9090
    networks:
      - jenkins
    volumes:
      #- ./prometheus:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # - type: bind
      #   source: ./prometheus/prometheus.yml
      #   target: /etc/prometheus/prometheus.yml
      #- ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'    

  influxdb:
    image: influxdb:1.7.9
    container_name: influxdb
    restart: unless-stopped
    networks:
      - jenkins
    environment:
      - INFLUXDB_DATA_MAX_SERIES_PER_DATABASE=0
      - INFLUXDB_DATA_MAX_VALUES_PER_TAG=0
    ports:
      - 8086:8086
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - ./influxdb_data:/var/lib/influxdb

  jenkins:    
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    image:
      ghcr.io/ababushk/jenkins-observability-talk:2.277.3-jdk11
    restart:
      unless-stopped
    ulimits:
      nofile:
        soft: 98304
        hard: 98304
    # network_mode: "host" # TODO: to display hostname of host in filebeat
    networks:
      - jenkins
      - kind
    ports:
      - "8080:8080"
      - "50000:50000" # JNLP agents port
      - "5022:22" # SSH port

    logging:
      driver: json-file
      options:
        max-size: 4g
    volumes:
      # - ./data:/var/jenkins_home:rw # only until I'll create perfect immutable image
      - ./builds:/var/jenkins_home/builds:rw
      - ./custom_logs:/var/jenkins_home/custom_logs:rw
      #- ./secrets:/run/secrets
