unclassified:
  prometheusConfiguration:
    appendParamLabel: true
    appendStatusLabel: true
    collectDiskUsage: true
    collectingMetricsPeriodInSeconds: 15
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: "default"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
    processingDisabledBuilds: false
    useAuthenticatedEndpoint: false